s/:grinning:/😀/g
s/:smiley:/😃/g
s/:smile:/😄/g
s/:grin:/😁/g
s/:\(laughing\|satisfied\):/😆/g
s/:sweat_smile:/😅/g
s/:rofl:/🤣/g
s/:joy:/😂/g
s/:slightly_smiling_face:/🙂/g
s/:upside_down_face:/🙃/g
s/:wink:/😉/g
s/:blush:/😊/g
s/:innocent:/😇/g
s/:smiling_face_with_three_hearts:/🥰/g
s/:heart_eyes:/😍/g
s/:star_struck:/🤩/g
s/:kissing_heart:/😘/g
s/:kissing:/😗/g
s/:relaxed:/☺️/g
s/:kissing_closed_eyes:/😚/g
s/:kissing_smiling_eyes:/😙/g
s/:smiling_face_with_tear:/🥲/g
s/:yum:/😋/g
s/:stuck_out_tongue:/😛/g
s/:stuck_out_tongue_winking_eye:/😜/g
s/:zany_face:/🤪/g
s/:stuck_out_tongue_closed_eyes:/😝/g
s/:money_mouth_face:/🤑/g
s/:hugs:/🤗/g
s/:hand_over_mouth:/🤭/g
s/:shushing_face:/🤫/g
s/:thinking:/🤔/g
s/:zipper_mouth_face:/🤐/g
s/:raised_eyebrow:/🤨/g
s/:neutral_face:/😐/g
s/:expressionless:/😑/g
s/:no_mouth:/😶/g
s/:smirk:/😏/g
s/:unamused:/😒/g
s/:roll_eyes:/🙄/g
s/:grimacing:/😬/g
s/:lying_face:/🤥/g
s/:relieved:/😌/g
s/:pensive:/😔/g
s/:sleepy:/😪/g
s/:drooling_face:/🤤/g
s/:sleeping:/😴/g
s/:mask:/😷/g
s/:face_with_thermometer:/🤒/g
s/:face_with_head_bandage:/🤕/g
s/:nauseated_face:/🤢/g
s/:vomiting_face:/🤮/g
s/:sneezing_face:/🤧/g
s/:hot_face:/🥵/g
s/:cold_face:/🥶/g
s/:woozy_face:/🥴/g
s/:dizzy_face:/😵/g
s/:exploding_head:/🤯/g
s/:cowboy_hat_face:/🤠/g
s/:partying_face:/🥳/g
s/:disguised_face:/🥸/g
s/:sunglasses:/😎/g
s/:nerd_face:/🤓/g
s/:monocle_face:/🧐/g
s/:confused:/😕/g
s/:worried:/😟/g
s/:slightly_frowning_face:/🙁/g
s/:frowning_face:/☹️/g
s/:open_mouth:/😮/g
s/:hushed:/😯/g
s/:astonished:/😲/g
s/:flushed:/😳/g
s/:pleading_face:/🥺/g
s/:frowning:/😦/g
s/:anguished:/😧/g
s/:fearful:/😨/g
s/:cold_sweat:/😰/g
s/:disappointed_relieved:/😥/g
s/:cry:/😢/g
s/:sob:/😭/g
s/:scream:/😱/g
s/:confounded:/😖/g
s/:persevere:/😣/g
s/:disappointed:/😞/g
s/:sweat:/😓/g
s/:weary:/😩/g
s/:tired_face:/😫/g
s/:yawning_face:/🥱/g
s/:triumph:/😤/g
s/:\(rage\|pout\):/😡/g
s/:angry:/😠/g
s/:cursing_face:/🤬/g
s/:smiling_imp:/😈/g
s/:imp:/👿/g
s/:skull:/💀/g
s/:skull_and_crossbones:/☠️/g
s/:\(hankey\|poop\|shit\):/💩/g
s/:clown_face:/🤡/g
s/:japanese_ogre:/👹/g
s/:japanese_goblin:/👺/g
s/:ghost:/👻/g
s/:alien:/👽/g
s/:space_invader:/👾/g
s/:robot:/🤖/g
s/:smiley_cat:/😺/g
s/:smile_cat:/😸/g
s/:joy_cat:/😹/g
s/:heart_eyes_cat:/😻/g
s/:smirk_cat:/😼/g
s/:kissing_cat:/😽/g
s/:scream_cat:/🙀/g
s/:crying_cat_face:/😿/g
s/:pouting_cat:/😾/g
s/:see_no_evil:/🙈/g
s/:hear_no_evil:/🙉/g
s/:speak_no_evil:/🙊/g
s/:kiss:/💋/g
s/:love_letter:/💌/g
s/:cupid:/💘/g
s/:gift_heart:/💝/g
s/:sparkling_heart:/💖/g
s/:heartpulse:/💗/g
s/:heartbeat:/💓/g
s/:revolving_hearts:/💞/g
s/:two_hearts:/💕/g
s/:heart_decoration:/💟/g
s/:heavy_heart_exclamation:/❣️/g
s/:broken_heart:/💔/g
s/:heart:/❤️/g
s/:orange_heart:/🧡/g
s/:yellow_heart:/💛/g
s/:green_heart:/💚/g
s/:blue_heart:/💙/g
s/:purple_heart:/💜/g
s/:brown_heart:/🤎/g
s/:black_heart:/🖤/g
s/:white_heart:/🤍/g
s/:100:/💯/g
s/:anger:/💢/g
s/:\(boom\|collision\):/💥/g
s/:dizzy:/💫/g
s/:sweat_drops:/💦/g
s/:dash:/💨/g
s/:hole:/🕳️/g
s/:bomb:/💣/g
s/:speech_balloon:/💬/g
s/:eye_speech_bubble:/👁️‍🗨️/g
s/:left_speech_bubble:/🗨️/g
s/:right_anger_bubble:/🗯️/g
s/:thought_balloon:/💭/g
s/:zzz:/💤/g
s/:wave:/👋/g
s/:raised_back_of_hand:/🤚/g
s/:raised_hand_with_fingers_splayed:/🖐️/g
s/:\(hand\|raised_hand\):/✋/g
s/:vulcan_salute:/🖖/g
s/:ok_hand:/👌/g
s/:pinched_fingers:/🤌/g
s/:pinching_hand:/🤏/g
s/:v:/✌️/g
s/:crossed_fingers:/🤞/g
s/:love_you_gesture:/🤟/g
s/:metal:/🤘/g
s/:call_me_hand:/🤙/g
s/:point_left:/👈/g
s/:point_right:/👉/g
s/:point_up_2:/👆/g
s/:\(middle_finger\|fu\):/🖕/g
s/:point_down:/👇/g
s/:point_up:/☝️/g
s/:\(+1\|thumbsup\):/👍/g
s/:\(-1\|thumbsdown\):/👎/g
s/:\(fist_raised\|fist\):/✊/g
s/:\(fist_oncoming\|facepunch\|punch\):/👊/g
s/:fist_left:/🤛/g
s/:fist_right:/🤜/g
s/:clap:/👏/g
s/:raised_hands:/🙌/g
s/:open_hands:/👐/g
s/:palms_up_together:/🤲/g
s/:handshake:/🤝/g
s/:pray:/🙏/g
s/:writing_hand:/✍️/g
s/:nail_care:/💅/g
s/:selfie:/🤳/g
s/:muscle:/💪/g
s/:mechanical_arm:/🦾/g
s/:mechanical_leg:/🦿/g
s/:leg:/🦵/g
s/:foot:/🦶/g
s/:ear:/👂/g
s/:ear_with_hearing_aid:/🦻/g
s/:nose:/👃/g
s/:brain:/🧠/g
s/:anatomical_heart:/🫀/g
s/:lungs:/🫁/g
s/:tooth:/🦷/g
s/:bone:/🦴/g
s/:eyes:/👀/g
s/:eye:/👁️/g
s/:tongue:/👅/g
s/:lips:/👄/g
s/:baby:/👶/g
s/:child:/🧒/g
s/:boy:/👦/g
s/:girl:/👧/g
s/:adult:/🧑/g
s/:blond_haired_person:/👱/g
s/:man:/👨/g
s/:bearded_person:/🧔/g
s/:red_haired_man:/👨‍🦰/g
s/:curly_haired_man:/👨‍🦱/g
s/:white_haired_man:/👨‍🦳/g
s/:bald_man:/👨‍🦲/g
s/:woman:/👩/g
s/:red_haired_woman:/👩‍🦰/g
s/:person_red_hair:/🧑‍🦰/g
s/:curly_haired_woman:/👩‍🦱/g
s/:person_curly_hair:/🧑‍🦱/g
s/:white_haired_woman:/👩‍🦳/g
s/:person_white_hair:/🧑‍🦳/g
s/:bald_woman:/👩‍🦲/g
s/:person_bald:/🧑‍🦲/g
s/:\(blond_haired_woman\|blonde_woman\):/👱‍♀️/g
s/:blond_haired_man:/👱‍♂️/g
s/:older_adult:/🧓/g
s/:older_man:/👴/g
s/:older_woman:/👵/g
s/:frowning_person:/🙍/g
s/:frowning_man:/🙍‍♂️/g
s/:frowning_woman:/🙍‍♀️/g
s/:pouting_face:/🙎/g
s/:pouting_man:/🙎‍♂️/g
s/:pouting_woman:/🙎‍♀️/g
s/:no_good:/🙅/g
s/:\(no_good_man\|ng_man\):/🙅‍♂️/g
s/:\(no_good_woman\|ng_woman\):/🙅‍♀️/g
s/:ok_person:/🙆/g
s/:ok_man:/🙆‍♂️/g
s/:ok_woman:/🙆‍♀️/g
s/:\(tipping_hand_person\|information_desk_person\):/💁/g
s/:\(tipping_hand_man\|sassy_man\):/💁‍♂️/g
s/:\(tipping_hand_woman\|sassy_woman\):/💁‍♀️/g
s/:raising_hand:/🙋/g
s/:raising_hand_man:/🙋‍♂️/g
s/:raising_hand_woman:/🙋‍♀️/g
s/:deaf_person:/🧏/g
s/:deaf_man:/🧏‍♂️/g
s/:deaf_woman:/🧏‍♀️/g
s/:bow:/🙇/g
s/:bowing_man:/🙇‍♂️/g
s/:bowing_woman:/🙇‍♀️/g
s/:facepalm:/🤦/g
s/:man_facepalming:/🤦‍♂️/g
s/:woman_facepalming:/🤦‍♀️/g
s/:shrug:/🤷/g
s/:man_shrugging:/🤷‍♂️/g
s/:woman_shrugging:/🤷‍♀️/g
s/:health_worker:/🧑‍⚕️/g
s/:man_health_worker:/👨‍⚕️/g
s/:woman_health_worker:/👩‍⚕️/g
s/:student:/🧑‍🎓/g
s/:man_student:/👨‍🎓/g
s/:woman_student:/👩‍🎓/g
s/:teacher:/🧑‍🏫/g
s/:man_teacher:/👨‍🏫/g
s/:woman_teacher:/👩‍🏫/g
s/:judge:/🧑‍⚖️/g
s/:man_judge:/👨‍⚖️/g
s/:woman_judge:/👩‍⚖️/g
s/:farmer:/🧑‍🌾/g
s/:man_farmer:/👨‍🌾/g
s/:woman_farmer:/👩‍🌾/g
s/:cook:/🧑‍🍳/g
s/:man_cook:/👨‍🍳/g
s/:woman_cook:/👩‍🍳/g
s/:mechanic:/🧑‍🔧/g
s/:man_mechanic:/👨‍🔧/g
s/:woman_mechanic:/👩‍🔧/g
s/:factory_worker:/🧑‍🏭/g
s/:man_factory_worker:/👨‍🏭/g
s/:woman_factory_worker:/👩‍🏭/g
s/:office_worker:/🧑‍💼/g
s/:man_office_worker:/👨‍💼/g
s/:woman_office_worker:/👩‍💼/g
s/:scientist:/🧑‍🔬/g
s/:man_scientist:/👨‍🔬/g
s/:woman_scientist:/👩‍🔬/g
s/:technologist:/🧑‍💻/g
s/:man_technologist:/👨‍💻/g
s/:woman_technologist:/👩‍💻/g
s/:singer:/🧑‍🎤/g
s/:man_singer:/👨‍🎤/g
s/:woman_singer:/👩‍🎤/g
s/:artist:/🧑‍🎨/g
s/:man_artist:/👨‍🎨/g
s/:woman_artist:/👩‍🎨/g
s/:pilot:/🧑‍✈️/g
s/:man_pilot:/👨‍✈️/g
s/:woman_pilot:/👩‍✈️/g
s/:astronaut:/🧑‍🚀/g
s/:man_astronaut:/👨‍🚀/g
s/:woman_astronaut:/👩‍🚀/g
s/:firefighter:/🧑‍🚒/g
s/:man_firefighter:/👨‍🚒/g
s/:woman_firefighter:/👩‍🚒/g
s/:\(police_officer\|cop\):/👮/g
s/:policeman:/👮‍♂️/g
s/:policewoman:/👮‍♀️/g
s/:detective:/🕵️/g
s/:male_detective:/🕵️‍♂️/g
s/:female_detective:/🕵️‍♀️/g
s/:guard:/💂/g
s/:guardsman:/💂‍♂️/g
s/:guardswoman:/💂‍♀️/g
s/:ninja:/🥷/g
s/:construction_worker:/👷/g
s/:construction_worker_man:/👷‍♂️/g
s/:construction_worker_woman:/👷‍♀️/g
s/:prince:/🤴/g
s/:princess:/👸/g
s/:person_with_turban:/👳/g
s/:man_with_turban:/👳‍♂️/g
s/:woman_with_turban:/👳‍♀️/g
s/:man_with_gua_pi_mao:/👲/g
s/:woman_with_headscarf:/🧕/g
s/:person_in_tuxedo:/🤵/g
s/:man_in_tuxedo:/🤵‍♂️/g
s/:woman_in_tuxedo:/🤵‍♀️/g
s/:person_with_veil:/👰/g
s/:man_with_veil:/👰‍♂️/g
s/:\(woman_with_veil\|bride_with_veil\):/👰‍♀️/g
s/:pregnant_woman:/🤰/g
s/:breast_feeding:/🤱/g
s/:woman_feeding_baby:/👩‍🍼/g
s/:man_feeding_baby:/👨‍🍼/g
s/:person_feeding_baby:/🧑‍🍼/g
s/:angel:/👼/g
s/:santa:/🎅/g
s/:mrs_claus:/🤶/g
s/:mx_claus:/🧑‍🎄/g
s/:superhero:/🦸/g
s/:superhero_man:/🦸‍♂️/g
s/:superhero_woman:/🦸‍♀️/g
s/:supervillain:/🦹/g
s/:supervillain_man:/🦹‍♂️/g
s/:supervillain_woman:/🦹‍♀️/g
s/:mage:/🧙/g
s/:mage_man:/🧙‍♂️/g
s/:mage_woman:/🧙‍♀️/g
s/:fairy:/🧚/g
s/:fairy_man:/🧚‍♂️/g
s/:fairy_woman:/🧚‍♀️/g
s/:vampire:/🧛/g
s/:vampire_man:/🧛‍♂️/g
s/:vampire_woman:/🧛‍♀️/g
s/:merperson:/🧜/g
s/:merman:/🧜‍♂️/g
s/:mermaid:/🧜‍♀️/g
s/:elf:/🧝/g
s/:elf_man:/🧝‍♂️/g
s/:elf_woman:/🧝‍♀️/g
s/:genie:/🧞/g
s/:genie_man:/🧞‍♂️/g
s/:genie_woman:/🧞‍♀️/g
s/:zombie:/🧟/g
s/:zombie_man:/🧟‍♂️/g
s/:zombie_woman:/🧟‍♀️/g
s/:massage:/💆/g
s/:massage_man:/💆‍♂️/g
s/:massage_woman:/💆‍♀️/g
s/:haircut:/💇/g
s/:haircut_man:/💇‍♂️/g
s/:haircut_woman:/💇‍♀️/g
s/:walking:/🚶/g
s/:walking_man:/🚶‍♂️/g
s/:walking_woman:/🚶‍♀️/g
s/:standing_person:/🧍/g
s/:standing_man:/🧍‍♂️/g
s/:standing_woman:/🧍‍♀️/g
s/:kneeling_person:/🧎/g
s/:kneeling_man:/🧎‍♂️/g
s/:kneeling_woman:/🧎‍♀️/g
s/:person_with_probing_cane:/🧑‍🦯/g
s/:man_with_probing_cane:/👨‍🦯/g
s/:woman_with_probing_cane:/👩‍🦯/g
s/:person_in_motorized_wheelchair:/🧑‍🦼/g
s/:man_in_motorized_wheelchair:/👨‍🦼/g
s/:woman_in_motorized_wheelchair:/👩‍🦼/g
s/:person_in_manual_wheelchair:/🧑‍🦽/g
s/:man_in_manual_wheelchair:/👨‍🦽/g
s/:woman_in_manual_wheelchair:/👩‍🦽/g
s/:\(runner\|running\):/🏃/g
s/:running_man:/🏃‍♂️/g
s/:running_woman:/🏃‍♀️/g
s/:\(woman_dancing\|dancer\):/💃/g
s/:man_dancing:/🕺/g
s/:business_suit_levitating:/🕴️/g
s/:dancers:/👯/g
s/:dancing_men:/👯‍♂️/g
s/:dancing_women:/👯‍♀️/g
s/:sauna_person:/🧖/g
s/:sauna_man:/🧖‍♂️/g
s/:sauna_woman:/🧖‍♀️/g
s/:climbing:/🧗/g
s/:climbing_man:/🧗‍♂️/g
s/:climbing_woman:/🧗‍♀️/g
s/:person_fencing:/🤺/g
s/:horse_racing:/🏇/g
s/:skier:/⛷️/g
s/:snowboarder:/🏂/g
s/:golfing:/🏌️/g
s/:golfing_man:/🏌️‍♂️/g
s/:golfing_woman:/🏌️‍♀️/g
s/:surfer:/🏄/g
s/:surfing_man:/🏄‍♂️/g
s/:surfing_woman:/🏄‍♀️/g
s/:rowboat:/🚣/g
s/:rowing_man:/🚣‍♂️/g
s/:rowing_woman:/🚣‍♀️/g
s/:swimmer:/🏊/g
s/:swimming_man:/🏊‍♂️/g
s/:swimming_woman:/🏊‍♀️/g
s/:bouncing_ball_person:/⛹️/g
s/:\(bouncing_ball_man\|basketball_man\):/⛹️‍♂️/g
s/:\(bouncing_ball_woman\|basketball_woman\):/⛹️‍♀️/g
s/:weight_lifting:/🏋️/g
s/:weight_lifting_man:/🏋️‍♂️/g
s/:weight_lifting_woman:/🏋️‍♀️/g
s/:bicyclist:/🚴/g
s/:biking_man:/🚴‍♂️/g
s/:biking_woman:/🚴‍♀️/g
s/:mountain_bicyclist:/🚵/g
s/:mountain_biking_man:/🚵‍♂️/g
s/:mountain_biking_woman:/🚵‍♀️/g
s/:cartwheeling:/🤸/g
s/:man_cartwheeling:/🤸‍♂️/g
s/:woman_cartwheeling:/🤸‍♀️/g
s/:wrestling:/🤼/g
s/:men_wrestling:/🤼‍♂️/g
s/:women_wrestling:/🤼‍♀️/g
s/:water_polo:/🤽/g
s/:man_playing_water_polo:/🤽‍♂️/g
s/:woman_playing_water_polo:/🤽‍♀️/g
s/:handball_person:/🤾/g
s/:man_playing_handball:/🤾‍♂️/g
s/:woman_playing_handball:/🤾‍♀️/g
s/:juggling_person:/🤹/g
s/:man_juggling:/🤹‍♂️/g
s/:woman_juggling:/🤹‍♀️/g
s/:lotus_position:/🧘/g
s/:lotus_position_man:/🧘‍♂️/g
s/:lotus_position_woman:/🧘‍♀️/g
s/:bath:/🛀/g
s/:sleeping_bed:/🛌/g
s/:people_holding_hands:/🧑‍🤝‍🧑/g
s/:two_women_holding_hands:/👭/g
s/:couple:/👫/g
s/:two_men_holding_hands:/👬/g
s/:couplekiss:/💏/g
s/:couplekiss_man_woman:/👩‍❤️‍💋‍👨/g
s/:couplekiss_man_man:/👨‍❤️‍💋‍👨/g
s/:couplekiss_woman_woman:/👩‍❤️‍💋‍👩/g
s/:couple_with_heart:/💑/g
s/:couple_with_heart_woman_man:/👩‍❤️‍👨/g
s/:couple_with_heart_man_man:/👨‍❤️‍👨/g
s/:couple_with_heart_woman_woman:/👩‍❤️‍👩/g
s/:family:/👪/g
s/:family_man_woman_boy:/👨‍👩‍👦/g
s/:family_man_woman_girl:/👨‍👩‍👧/g
s/:family_man_woman_girl_boy:/👨‍👩‍👧‍👦/g
s/:family_man_woman_boy_boy:/👨‍👩‍👦‍👦/g
s/:family_man_woman_girl_girl:/👨‍👩‍👧‍👧/g
s/:family_man_man_boy:/👨‍👨‍👦/g
s/:family_man_man_girl:/👨‍👨‍👧/g
s/:family_man_man_girl_boy:/👨‍👨‍👧‍👦/g
s/:family_man_man_boy_boy:/👨‍👨‍👦‍👦/g
s/:family_man_man_girl_girl:/👨‍👨‍👧‍👧/g
s/:family_woman_woman_boy:/👩‍👩‍👦/g
s/:family_woman_woman_girl:/👩‍👩‍👧/g
s/:family_woman_woman_girl_boy:/👩‍👩‍👧‍👦/g
s/:family_woman_woman_boy_boy:/👩‍👩‍👦‍👦/g
s/:family_woman_woman_girl_girl:/👩‍👩‍👧‍👧/g
s/:family_man_boy:/👨‍👦/g
s/:family_man_boy_boy:/👨‍👦‍👦/g
s/:family_man_girl:/👨‍👧/g
s/:family_man_girl_boy:/👨‍👧‍👦/g
s/:family_man_girl_girl:/👨‍👧‍👧/g
s/:family_woman_boy:/👩‍👦/g
s/:family_woman_boy_boy:/👩‍👦‍👦/g
s/:family_woman_girl:/👩‍👧/g
s/:family_woman_girl_boy:/👩‍👧‍👦/g
s/:family_woman_girl_girl:/👩‍👧‍👧/g
s/:speaking_head:/🗣️/g
s/:bust_in_silhouette:/👤/g
s/:busts_in_silhouette:/👥/g
s/:people_hugging:/🫂/g
s/:footprints:/👣/g
s/:monkey_face:/🐵/g
s/:monkey:/🐒/g
s/:gorilla:/🦍/g
s/:orangutan:/🦧/g
s/:dog:/🐶/g
s/:dog2:/🐕/g
s/:guide_dog:/🦮/g
s/:service_dog:/🐕‍🦺/g
s/:poodle:/🐩/g
s/:wolf:/🐺/g
s/:fox_face:/🦊/g
s/:raccoon:/🦝/g
s/:cat:/🐱/g
s/:cat2:/🐈/g
s/:black_cat:/🐈‍⬛/g
s/:lion:/🦁/g
s/:tiger:/🐯/g
s/:tiger2:/🐅/g
s/:leopard:/🐆/g
s/:horse:/🐴/g
s/:racehorse:/🐎/g
s/:unicorn:/🦄/g
s/:zebra:/🦓/g
s/:deer:/🦌/g
s/:bison:/🦬/g
s/:cow:/🐮/g
s/:ox:/🐂/g
s/:water_buffalo:/🐃/g
s/:cow2:/🐄/g
s/:pig:/🐷/g
s/:pig2:/🐖/g
s/:boar:/🐗/g
s/:pig_nose:/🐽/g
s/:ram:/🐏/g
s/:sheep:/🐑/g
s/:goat:/🐐/g
s/:dromedary_camel:/🐪/g
s/:camel:/🐫/g
s/:llama:/🦙/g
s/:giraffe:/🦒/g
s/:elephant:/🐘/g
s/:mammoth:/🦣/g
s/:rhinoceros:/🦏/g
s/:hippopotamus:/🦛/g
s/:mouse:/🐭/g
s/:mouse2:/🐁/g
s/:rat:/🐀/g
s/:hamster:/🐹/g
s/:rabbit:/🐰/g
s/:rabbit2:/🐇/g
s/:chipmunk:/🐿️/g
s/:beaver:/🦫/g
s/:hedgehog:/🦔/g
s/:bat:/🦇/g
s/:bear:/🐻/g
s/:polar_bear:/🐻‍❄️/g
s/:koala:/🐨/g
s/:panda_face:/🐼/g
s/:sloth:/🦥/g
s/:otter:/🦦/g
s/:skunk:/🦨/g
s/:kangaroo:/🦘/g
s/:badger:/🦡/g
s/:\(feet\|paw_prints\):/🐾/g
s/:turkey:/🦃/g
s/:chicken:/🐔/g
s/:rooster:/🐓/g
s/:hatching_chick:/🐣/g
s/:baby_chick:/🐤/g
s/:hatched_chick:/🐥/g
s/:bird:/🐦/g
s/:penguin:/🐧/g
s/:dove:/🕊️/g
s/:eagle:/🦅/g
s/:duck:/🦆/g
s/:swan:/🦢/g
s/:owl:/🦉/g
s/:dodo:/🦤/g
s/:feather:/🪶/g
s/:flamingo:/🦩/g
s/:peacock:/🦚/g
s/:parrot:/🦜/g
s/:frog:/🐸/g
s/:crocodile:/🐊/g
s/:turtle:/🐢/g
s/:lizard:/🦎/g
s/:snake:/🐍/g
s/:dragon_face:/🐲/g
s/:dragon:/🐉/g
s/:sauropod:/🦕/g
s/:t-rex:/🦖/g
s/:whale:/🐳/g
s/:whale2:/🐋/g
s/:\(dolphin\|flipper\):/🐬/g
s/:seal:/🦭/g
s/:fish:/🐟/g
s/:tropical_fish:/🐠/g
s/:blowfish:/🐡/g
s/:shark:/🦈/g
s/:octopus:/🐙/g
s/:shell:/🐚/g
s/:snail:/🐌/g
s/:butterfly:/🦋/g
s/:bug:/🐛/g
s/:ant:/🐜/g
s/:\(bee\|honeybee\):/🐝/g
s/:beetle:/🪲/g
s/:lady_beetle:/🐞/g
s/:cricket:/🦗/g
s/:cockroach:/🪳/g
s/:spider:/🕷️/g
s/:spider_web:/🕸️/g
s/:scorpion:/🦂/g
s/:mosquito:/🦟/g
s/:fly:/🪰/g
s/:worm:/🪱/g
s/:microbe:/🦠/g
s/:bouquet:/💐/g
s/:cherry_blossom:/🌸/g
s/:white_flower:/💮/g
s/:rosette:/🏵️/g
s/:rose:/🌹/g
s/:wilted_flower:/🥀/g
s/:hibiscus:/🌺/g
s/:sunflower:/🌻/g
s/:blossom:/🌼/g
s/:tulip:/🌷/g
s/:seedling:/🌱/g
s/:potted_plant:/🪴/g
s/:evergreen_tree:/🌲/g
s/:deciduous_tree:/🌳/g
s/:palm_tree:/🌴/g
s/:cactus:/🌵/g
s/:ear_of_rice:/🌾/g
s/:herb:/🌿/g
s/:shamrock:/☘️/g
s/:four_leaf_clover:/🍀/g
s/:maple_leaf:/🍁/g
s/:fallen_leaf:/🍂/g
s/:leaves:/🍃/g
s/:grapes:/🍇/g
s/:melon:/🍈/g
s/:watermelon:/🍉/g
s/:\(tangerine\|orange\|mandarin\):/🍊/g
s/:lemon:/🍋/g
s/:banana:/🍌/g
s/:pineapple:/🍍/g
s/:mango:/🥭/g
s/:apple:/🍎/g
s/:green_apple:/🍏/g
s/:pear:/🍐/g
s/:peach:/🍑/g
s/:cherries:/🍒/g
s/:strawberry:/🍓/g
s/:blueberries:/🫐/g
s/:kiwi_fruit:/🥝/g
s/:tomato:/🍅/g
s/:olive:/🫒/g
s/:coconut:/🥥/g
s/:avocado:/🥑/g
s/:eggplant:/🍆/g
s/:potato:/🥔/g
s/:carrot:/🥕/g
s/:corn:/🌽/g
s/:hot_pepper:/🌶️/g
s/:bell_pepper:/🫑/g
s/:cucumber:/🥒/g
s/:leafy_green:/🥬/g
s/:broccoli:/🥦/g
s/:garlic:/🧄/g
s/:onion:/🧅/g
s/:mushroom:/🍄/g
s/:peanuts:/🥜/g
s/:chestnut:/🌰/g
s/:bread:/🍞/g
s/:croissant:/🥐/g
s/:baguette_bread:/🥖/g
s/:flatbread:/🫓/g
s/:pretzel:/🥨/g
s/:bagel:/🥯/g
s/:pancakes:/🥞/g
s/:waffle:/🧇/g
s/:cheese:/🧀/g
s/:meat_on_bone:/🍖/g
s/:poultry_leg:/🍗/g
s/:cut_of_meat:/🥩/g
s/:bacon:/🥓/g
s/:hamburger:/🍔/g
s/:fries:/🍟/g
s/:pizza:/🍕/g
s/:hotdog:/🌭/g
s/:sandwich:/🥪/g
s/:taco:/🌮/g
s/:burrito:/🌯/g
s/:tamale:/🫔/g
s/:stuffed_flatbread:/🥙/g
s/:falafel:/🧆/g
s/:egg:/🥚/g
s/:fried_egg:/🍳/g
s/:shallow_pan_of_food:/🥘/g
s/:stew:/🍲/g
s/:fondue:/🫕/g
s/:bowl_with_spoon:/🥣/g
s/:green_salad:/🥗/g
s/:popcorn:/🍿/g
s/:butter:/🧈/g
s/:salt:/🧂/g
s/:canned_food:/🥫/g
s/:bento:/🍱/g
s/:rice_cracker:/🍘/g
s/:rice_ball:/🍙/g
s/:rice:/🍚/g
s/:curry:/🍛/g
s/:ramen:/🍜/g
s/:spaghetti:/🍝/g
s/:sweet_potato:/🍠/g
s/:oden:/🍢/g
s/:sushi:/🍣/g
s/:fried_shrimp:/🍤/g
s/:fish_cake:/🍥/g
s/:moon_cake:/🥮/g
s/:dango:/🍡/g
s/:dumpling:/🥟/g
s/:fortune_cookie:/🥠/g
s/:takeout_box:/🥡/g
s/:crab:/🦀/g
s/:lobster:/🦞/g
s/:shrimp:/🦐/g
s/:squid:/🦑/g
s/:oyster:/🦪/g
s/:icecream:/🍦/g
s/:shaved_ice:/🍧/g
s/:ice_cream:/🍨/g
s/:doughnut:/🍩/g
s/:cookie:/🍪/g
s/:birthday:/🎂/g
s/:cake:/🍰/g
s/:cupcake:/🧁/g
s/:pie:/🥧/g
s/:chocolate_bar:/🍫/g
s/:candy:/🍬/g
s/:lollipop:/🍭/g
s/:custard:/🍮/g
s/:honey_pot:/🍯/g
s/:baby_bottle:/🍼/g
s/:milk_glass:/🥛/g
s/:coffee:/☕/g
s/:teapot:/🫖/g
s/:tea:/🍵/g
s/:sake:/🍶/g
s/:champagne:/🍾/g
s/:wine_glass:/🍷/g
s/:cocktail:/🍸/g
s/:tropical_drink:/🍹/g
s/:beer:/🍺/g
s/:beers:/🍻/g
s/:clinking_glasses:/🥂/g
s/:tumbler_glass:/🥃/g
s/:cup_with_straw:/🥤/g
s/:bubble_tea:/🧋/g
s/:beverage_box:/🧃/g
s/:mate:/🧉/g
s/:ice_cube:/🧊/g
s/:chopsticks:/🥢/g
s/:plate_with_cutlery:/🍽️/g
s/:fork_and_knife:/🍴/g
s/:spoon:/🥄/g
s/:\(hocho\|knife\):/🔪/g
s/:amphora:/🏺/g
s/:earth_africa:/🌍/g
s/:earth_americas:/🌎/g
s/:earth_asia:/🌏/g
s/:globe_with_meridians:/🌐/g
s/:world_map:/🗺️/g
s/:japan:/🗾/g
s/:compass:/🧭/g
s/:mountain_snow:/🏔️/g
s/:mountain:/⛰️/g
s/:volcano:/🌋/g
s/:mount_fuji:/🗻/g
s/:camping:/🏕️/g
s/:beach_umbrella:/🏖️/g
s/:desert:/🏜️/g
s/:desert_island:/🏝️/g
s/:national_park:/🏞️/g
s/:stadium:/🏟️/g
s/:classical_building:/🏛️/g
s/:building_construction:/🏗️/g
s/:bricks:/🧱/g
s/:rock:/🪨/g
s/:wood:/🪵/g
s/:hut:/🛖/g
s/:houses:/🏘️/g
s/:derelict_house:/🏚️/g
s/:house:/🏠/g
s/:house_with_garden:/🏡/g
s/:office:/🏢/g
s/:post_office:/🏣/g
s/:european_post_office:/🏤/g
s/:hospital:/🏥/g
s/:bank:/🏦/g
s/:hotel:/🏨/g
s/:love_hotel:/🏩/g
s/:convenience_store:/🏪/g
s/:school:/🏫/g
s/:department_store:/🏬/g
s/:factory:/🏭/g
s/:japanese_castle:/🏯/g
s/:european_castle:/🏰/g
s/:wedding:/💒/g
s/:tokyo_tower:/🗼/g
s/:statue_of_liberty:/🗽/g
s/:church:/⛪/g
s/:mosque:/🕌/g
s/:hindu_temple:/🛕/g
s/:synagogue:/🕍/g
s/:shinto_shrine:/⛩️/g
s/:kaaba:/🕋/g
s/:fountain:/⛲/g
s/:tent:/⛺/g
s/:foggy:/🌁/g
s/:night_with_stars:/🌃/g
s/:cityscape:/🏙️/g
s/:sunrise_over_mountains:/🌄/g
s/:sunrise:/🌅/g
s/:city_sunset:/🌆/g
s/:city_sunrise:/🌇/g
s/:bridge_at_night:/🌉/g
s/:hotsprings:/♨️/g
s/:carousel_horse:/🎠/g
s/:ferris_wheel:/🎡/g
s/:roller_coaster:/🎢/g
s/:barber:/💈/g
s/:circus_tent:/🎪/g
s/:steam_locomotive:/🚂/g
s/:railway_car:/🚃/g
s/:bullettrain_side:/🚄/g
s/:bullettrain_front:/🚅/g
s/:train2:/🚆/g
s/:metro:/🚇/g
s/:light_rail:/🚈/g
s/:station:/🚉/g
s/:tram:/🚊/g
s/:monorail:/🚝/g
s/:mountain_railway:/🚞/g
s/:train:/🚋/g
s/:bus:/🚌/g
s/:oncoming_bus:/🚍/g
s/:trolleybus:/🚎/g
s/:minibus:/🚐/g
s/:ambulance:/🚑/g
s/:fire_engine:/🚒/g
s/:police_car:/🚓/g
s/:oncoming_police_car:/🚔/g
s/:taxi:/🚕/g
s/:oncoming_taxi:/🚖/g
s/:\(car\|red_car\):/🚗/g
s/:oncoming_automobile:/🚘/g
s/:blue_car:/🚙/g
s/:pickup_truck:/🛻/g
s/:truck:/🚚/g
s/:articulated_lorry:/🚛/g
s/:tractor:/🚜/g
s/:racing_car:/🏎️/g
s/:motorcycle:/🏍️/g
s/:motor_scooter:/🛵/g
s/:manual_wheelchair:/🦽/g
s/:motorized_wheelchair:/🦼/g
s/:auto_rickshaw:/🛺/g
s/:bike:/🚲/g
s/:kick_scooter:/🛴/g
s/:skateboard:/🛹/g
s/:roller_skate:/🛼/g
s/:busstop:/🚏/g
s/:motorway:/🛣️/g
s/:railway_track:/🛤️/g
s/:oil_drum:/🛢️/g
s/:fuelpump:/⛽/g
s/:rotating_light:/🚨/g
s/:traffic_light:/🚥/g
s/:vertical_traffic_light:/🚦/g
s/:stop_sign:/🛑/g
s/:construction:/🚧/g
s/:anchor:/⚓/g
s/:\(boat\|sailboat\):/⛵/g
s/:canoe:/🛶/g
s/:speedboat:/🚤/g
s/:passenger_ship:/🛳️/g
s/:ferry:/⛴️/g
s/:motor_boat:/🛥️/g
s/:ship:/🚢/g
s/:airplane:/✈️/g
s/:small_airplane:/🛩️/g
s/:flight_departure:/🛫/g
s/:flight_arrival:/🛬/g
s/:parachute:/🪂/g
s/:seat:/💺/g
s/:helicopter:/🚁/g
s/:suspension_railway:/🚟/g
s/:mountain_cableway:/🚠/g
s/:aerial_tramway:/🚡/g
s/:artificial_satellite:/🛰️/g
s/:rocket:/🚀/g
s/:flying_saucer:/🛸/g
s/:bellhop_bell:/🛎️/g
s/:luggage:/🧳/g
s/:hourglass:/⌛/g
s/:hourglass_flowing_sand:/⏳/g
s/:watch:/⌚/g
s/:alarm_clock:/⏰/g
s/:stopwatch:/⏱️/g
s/:timer_clock:/⏲️/g
s/:mantelpiece_clock:/🕰️/g
s/:clock12:/🕛/g
s/:clock1230:/🕧/g
s/:clock1:/🕐/g
s/:clock130:/🕜/g
s/:clock2:/🕑/g
s/:clock230:/🕝/g
s/:clock3:/🕒/g
s/:clock330:/🕞/g
s/:clock4:/🕓/g
s/:clock430:/🕟/g
s/:clock5:/🕔/g
s/:clock530:/🕠/g
s/:clock6:/🕕/g
s/:clock630:/🕡/g
s/:clock7:/🕖/g
s/:clock730:/🕢/g
s/:clock8:/🕗/g
s/:clock830:/🕣/g
s/:clock9:/🕘/g
s/:clock930:/🕤/g
s/:clock10:/🕙/g
s/:clock1030:/🕥/g
s/:clock11:/🕚/g
s/:clock1130:/🕦/g
s/:new_moon:/🌑/g
s/:waxing_crescent_moon:/🌒/g
s/:first_quarter_moon:/🌓/g
s/:\(moon\|waxing_gibbous_moon\):/🌔/g
s/:full_moon:/🌕/g
s/:waning_gibbous_moon:/🌖/g
s/:last_quarter_moon:/🌗/g
s/:waning_crescent_moon:/🌘/g
s/:crescent_moon:/🌙/g
s/:new_moon_with_face:/🌚/g
s/:first_quarter_moon_with_face:/🌛/g
s/:last_quarter_moon_with_face:/🌜/g
s/:thermometer:/🌡️/g
s/:sunny:/☀️/g
s/:full_moon_with_face:/🌝/g
s/:sun_with_face:/🌞/g
s/:ringed_planet:/🪐/g
s/:star:/⭐/g
s/:star2:/🌟/g
s/:stars:/🌠/g
s/:milky_way:/🌌/g
s/:cloud:/☁️/g
s/:partly_sunny:/⛅/g
s/:cloud_with_lightning_and_rain:/⛈️/g
s/:sun_behind_small_cloud:/🌤️/g
s/:sun_behind_large_cloud:/🌥️/g
s/:sun_behind_rain_cloud:/🌦️/g
s/:cloud_with_rain:/🌧️/g
s/:cloud_with_snow:/🌨️/g
s/:cloud_with_lightning:/🌩️/g
s/:tornado:/🌪️/g
s/:fog:/🌫️/g
s/:wind_face:/🌬️/g
s/:cyclone:/🌀/g
s/:rainbow:/🌈/g
s/:closed_umbrella:/🌂/g
s/:open_umbrella:/☂️/g
s/:umbrella:/☔/g
s/:parasol_on_ground:/⛱️/g
s/:zap:/⚡/g
s/:snowflake:/❄️/g
s/:snowman_with_snow:/☃️/g
s/:snowman:/⛄/g
s/:comet:/☄️/g
s/:fire:/🔥/g
s/:droplet:/💧/g
s/:ocean:/🌊/g
s/:jack_o_lantern:/🎃/g
s/:christmas_tree:/🎄/g
s/:fireworks:/🎆/g
s/:sparkler:/🎇/g
s/:firecracker:/🧨/g
s/:sparkles:/✨/g
s/:balloon:/🎈/g
s/:tada:/🎉/g
s/:confetti_ball:/🎊/g
s/:tanabata_tree:/🎋/g
s/:bamboo:/🎍/g
s/:dolls:/🎎/g
s/:flags:/🎏/g
s/:wind_chime:/🎐/g
s/:rice_scene:/🎑/g
s/:red_envelope:/🧧/g
s/:ribbon:/🎀/g
s/:gift:/🎁/g
s/:reminder_ribbon:/🎗️/g
s/:tickets:/🎟️/g
s/:ticket:/🎫/g
s/:medal_military:/🎖️/g
s/:trophy:/🏆/g
s/:medal_sports:/🏅/g
s/:1st_place_medal:/🥇/g
s/:2nd_place_medal:/🥈/g
s/:3rd_place_medal:/🥉/g
s/:soccer:/⚽/g
s/:baseball:/⚾/g
s/:softball:/🥎/g
s/:basketball:/🏀/g
s/:volleyball:/🏐/g
s/:football:/🏈/g
s/:rugby_football:/🏉/g
s/:tennis:/🎾/g
s/:flying_disc:/🥏/g
s/:bowling:/🎳/g
s/:cricket_game:/🏏/g
s/:field_hockey:/🏑/g
s/:ice_hockey:/🏒/g
s/:lacrosse:/🥍/g
s/:ping_pong:/🏓/g
s/:badminton:/🏸/g
s/:boxing_glove:/🥊/g
s/:martial_arts_uniform:/🥋/g
s/:goal_net:/🥅/g
s/:golf:/⛳/g
s/:ice_skate:/⛸️/g
s/:fishing_pole_and_fish:/🎣/g
s/:diving_mask:/🤿/g
s/:running_shirt_with_sash:/🎽/g
s/:ski:/🎿/g
s/:sled:/🛷/g
s/:curling_stone:/🥌/g
s/:dart:/🎯/g
s/:yo_yo:/🪀/g
s/:kite:/🪁/g
s/:8ball:/🎱/g
s/:crystal_ball:/🔮/g
s/:magic_wand:/🪄/g
s/:nazar_amulet:/🧿/g
s/:video_game:/🎮/g
s/:joystick:/🕹️/g
s/:slot_machine:/🎰/g
s/:game_die:/🎲/g
s/:jigsaw:/🧩/g
s/:teddy_bear:/🧸/g
s/:pinata:/🪅/g
s/:nesting_dolls:/🪆/g
s/:spades:/♠️/g
s/:hearts:/♥️/g
s/:diamonds:/♦️/g
s/:clubs:/♣️/g
s/:chess_pawn:/♟️/g
s/:black_joker:/🃏/g
s/:mahjong:/🀄/g
s/:flower_playing_cards:/🎴/g
s/:performing_arts:/🎭/g
s/:framed_picture:/🖼️/g
s/:art:/🎨/g
s/:thread:/🧵/g
s/:sewing_needle:/🪡/g
s/:yarn:/🧶/g
s/:knot:/🪢/g
s/:eyeglasses:/👓/g
s/:dark_sunglasses:/🕶️/g
s/:goggles:/🥽/g
s/:lab_coat:/🥼/g
s/:safety_vest:/🦺/g
s/:necktie:/👔/g
s/:\(shirt\|tshirt\):/👕/g
s/:jeans:/👖/g
s/:scarf:/🧣/g
s/:gloves:/🧤/g
s/:coat:/🧥/g
s/:socks:/🧦/g
s/:dress:/👗/g
s/:kimono:/👘/g
s/:sari:/🥻/g
s/:one_piece_swimsuit:/🩱/g
s/:swim_brief:/🩲/g
s/:shorts:/🩳/g
s/:bikini:/👙/g
s/:womans_clothes:/👚/g
s/:purse:/👛/g
s/:handbag:/👜/g
s/:pouch:/👝/g
s/:shopping:/🛍️/g
s/:school_satchel:/🎒/g
s/:thong_sandal:/🩴/g
s/:\(mans_shoe\|shoe\):/👞/g
s/:athletic_shoe:/👟/g
s/:hiking_boot:/🥾/g
s/:flat_shoe:/🥿/g
s/:high_heel:/👠/g
s/:sandal:/👡/g
s/:ballet_shoes:/🩰/g
s/:boot:/👢/g
s/:crown:/👑/g
s/:womans_hat:/👒/g
s/:tophat:/🎩/g
s/:mortar_board:/🎓/g
s/:billed_cap:/🧢/g
s/:military_helmet:/🪖/g
s/:rescue_worker_helmet:/⛑️/g
s/:prayer_beads:/📿/g
s/:lipstick:/💄/g
s/:ring:/💍/g
s/:gem:/💎/g
s/:mute:/🔇/g
s/:speaker:/🔈/g
s/:sound:/🔉/g
s/:loud_sound:/🔊/g
s/:loudspeaker:/📢/g
s/:mega:/📣/g
s/:postal_horn:/📯/g
s/:bell:/🔔/g
s/:no_bell:/🔕/g
s/:musical_score:/🎼/g
s/:musical_note:/🎵/g
s/:notes:/🎶/g
s/:studio_microphone:/🎙️/g
s/:level_slider:/🎚️/g
s/:control_knobs:/🎛️/g
s/:microphone:/🎤/g
s/:headphones:/🎧/g
s/:radio:/📻/g
s/:saxophone:/🎷/g
s/:accordion:/🪗/g
s/:guitar:/🎸/g
s/:musical_keyboard:/🎹/g
s/:trumpet:/🎺/g
s/:violin:/🎻/g
s/:banjo:/🪕/g
s/:drum:/🥁/g
s/:long_drum:/🪘/g
s/:iphone:/📱/g
s/:calling:/📲/g
s/:\(phone\|telephone\):/☎️/g
s/:telephone_receiver:/📞/g
s/:pager:/📟/g
s/:fax:/📠/g
s/:battery:/🔋/g
s/:electric_plug:/🔌/g
s/:computer:/💻/g
s/:desktop_computer:/🖥️/g
s/:printer:/🖨️/g
s/:keyboard:/⌨️/g
s/:computer_mouse:/🖱️/g
s/:trackball:/🖲️/g
s/:minidisc:/💽/g
s/:floppy_disk:/💾/g
s/:cd:/💿/g
s/:dvd:/📀/g
s/:abacus:/🧮/g
s/:movie_camera:/🎥/g
s/:film_strip:/🎞️/g
s/:film_projector:/📽️/g
s/:clapper:/🎬/g
s/:tv:/📺/g
s/:camera:/📷/g
s/:camera_flash:/📸/g
s/:video_camera:/📹/g
s/:vhs:/📼/g
s/:mag:/🔍/g
s/:mag_right:/🔎/g
s/:candle:/🕯️/g
s/:bulb:/💡/g
s/:flashlight:/🔦/g
s/:\(izakaya_lantern\|lantern\):/🏮/g
s/:diya_lamp:/🪔/g
s/:notebook_with_decorative_cover:/📔/g
s/:closed_book:/📕/g
s/:\(book\|open_book\):/📖/g
s/:green_book:/📗/g
s/:blue_book:/📘/g
s/:orange_book:/📙/g
s/:books:/📚/g
s/:notebook:/📓/g
s/:ledger:/📒/g
s/:page_with_curl:/📃/g
s/:scroll:/📜/g
s/:page_facing_up:/📄/g
s/:newspaper:/📰/g
s/:newspaper_roll:/🗞️/g
s/:bookmark_tabs:/📑/g
s/:bookmark:/🔖/g
s/:label:/🏷️/g
s/:moneybag:/💰/g
s/:coin:/🪙/g
s/:yen:/💴/g
s/:dollar:/💵/g
s/:euro:/💶/g
s/:pound:/💷/g
s/:money_with_wings:/💸/g
s/:credit_card:/💳/g
s/:receipt:/🧾/g
s/:chart:/💹/g
s/:envelope:/✉️/g
s/:\(email\|e-mail\):/📧/g
s/:incoming_envelope:/📨/g
s/:envelope_with_arrow:/📩/g
s/:outbox_tray:/📤/g
s/:inbox_tray:/📥/g
s/:package:/📦/g
s/:mailbox:/📫/g
s/:mailbox_closed:/📪/g
s/:mailbox_with_mail:/📬/g
s/:mailbox_with_no_mail:/📭/g
s/:postbox:/📮/g
s/:ballot_box:/🗳️/g
s/:pencil2:/✏️/g
s/:black_nib:/✒️/g
s/:fountain_pen:/🖋️/g
s/:pen:/🖊️/g
s/:paintbrush:/🖌️/g
s/:crayon:/🖍️/g
s/:\(memo\|pencil\):/📝/g
s/:briefcase:/💼/g
s/:file_folder:/📁/g
s/:open_file_folder:/📂/g
s/:card_index_dividers:/🗂️/g
s/:date:/📅/g
s/:calendar:/📆/g
s/:spiral_notepad:/🗒️/g
s/:spiral_calendar:/🗓️/g
s/:card_index:/📇/g
s/:chart_with_upwards_trend:/📈/g
s/:chart_with_downwards_trend:/📉/g
s/:bar_chart:/📊/g
s/:clipboard:/📋/g
s/:pushpin:/📌/g
s/:round_pushpin:/📍/g
s/:paperclip:/📎/g
s/:paperclips:/🖇️/g
s/:straight_ruler:/📏/g
s/:triangular_ruler:/📐/g
s/:scissors:/✂️/g
s/:card_file_box:/🗃️/g
s/:file_cabinet:/🗄️/g
s/:wastebasket:/🗑️/g
s/:lock:/🔒/g
s/:unlock:/🔓/g
s/:lock_with_ink_pen:/🔏/g
s/:closed_lock_with_key:/🔐/g
s/:key:/🔑/g
s/:old_key:/🗝️/g
s/:hammer:/🔨/g
s/:axe:/🪓/g
s/:pick:/⛏️/g
s/:hammer_and_pick:/⚒️/g
s/:hammer_and_wrench:/🛠️/g
s/:dagger:/🗡️/g
s/:crossed_swords:/⚔️/g
s/:gun:/🔫/g
s/:boomerang:/🪃/g
s/:bow_and_arrow:/🏹/g
s/:shield:/🛡️/g
s/:carpentry_saw:/🪚/g
s/:wrench:/🔧/g
s/:screwdriver:/🪛/g
s/:nut_and_bolt:/🔩/g
s/:gear:/⚙️/g
s/:clamp:/🗜️/g
s/:balance_scale:/⚖️/g
s/:probing_cane:/🦯/g
s/:link:/🔗/g
s/:chains:/⛓️/g
s/:hook:/🪝/g
s/:toolbox:/🧰/g
s/:magnet:/🧲/g
s/:ladder:/🪜/g
s/:alembic:/⚗️/g
s/:test_tube:/🧪/g
s/:petri_dish:/🧫/g
s/:dna:/🧬/g
s/:microscope:/🔬/g
s/:telescope:/🔭/g
s/:satellite:/📡/g
s/:syringe:/💉/g
s/:drop_of_blood:/🩸/g
s/:pill:/💊/g
s/:adhesive_bandage:/🩹/g
s/:stethoscope:/🩺/g
s/:door:/🚪/g
s/:elevator:/🛗/g
s/:mirror:/🪞/g
s/:window:/🪟/g
s/:bed:/🛏️/g
s/:couch_and_lamp:/🛋️/g
s/:chair:/🪑/g
s/:toilet:/🚽/g
s/:plunger:/🪠/g
s/:shower:/🚿/g
s/:bathtub:/🛁/g
s/:mouse_trap:/🪤/g
s/:razor:/🪒/g
s/:lotion_bottle:/🧴/g
s/:safety_pin:/🧷/g
s/:broom:/🧹/g
s/:basket:/🧺/g
s/:roll_of_paper:/🧻/g
s/:bucket:/🪣/g
s/:soap:/🧼/g
s/:toothbrush:/🪥/g
s/:sponge:/🧽/g
s/:fire_extinguisher:/🧯/g
s/:shopping_cart:/🛒/g
s/:smoking:/🚬/g
s/:coffin:/⚰️/g
s/:headstone:/🪦/g
s/:funeral_urn:/⚱️/g
s/:moyai:/🗿/g
s/:placard:/🪧/g
s/:atm:/🏧/g
s/:put_litter_in_its_place:/🚮/g
s/:potable_water:/🚰/g
s/:wheelchair:/♿/g
s/:mens:/🚹/g
s/:womens:/🚺/g
s/:restroom:/🚻/g
s/:baby_symbol:/🚼/g
s/:wc:/🚾/g
s/:passport_control:/🛂/g
s/:customs:/🛃/g
s/:baggage_claim:/🛄/g
s/:left_luggage:/🛅/g
s/:warning:/⚠️/g
s/:children_crossing:/🚸/g
s/:no_entry:/⛔/g
s/:no_entry_sign:/🚫/g
s/:no_bicycles:/🚳/g
s/:no_smoking:/🚭/g
s/:do_not_litter:/🚯/g
s/:non-potable_water:/🚱/g
s/:no_pedestrians:/🚷/g
s/:no_mobile_phones:/📵/g
s/:underage:/🔞/g
s/:radioactive:/☢️/g
s/:biohazard:/☣️/g
s/:arrow_up:/⬆️/g
s/:arrow_upper_right:/↗️/g
s/:arrow_right:/➡️/g
s/:arrow_lower_right:/↘️/g
s/:arrow_down:/⬇️/g
s/:arrow_lower_left:/↙️/g
s/:arrow_left:/⬅️/g
s/:arrow_upper_left:/↖️/g
s/:arrow_up_down:/↕️/g
s/:left_right_arrow:/↔️/g
s/:leftwards_arrow_with_hook:/↩️/g
s/:arrow_right_hook:/↪️/g
s/:arrow_heading_up:/⤴️/g
s/:arrow_heading_down:/⤵️/g
s/:arrows_clockwise:/🔃/g
s/:arrows_counterclockwise:/🔄/g
s/:back:/🔙/g
s/:end:/🔚/g
s/:on:/🔛/g
s/:soon:/🔜/g
s/:top:/🔝/g
s/:place_of_worship:/🛐/g
s/:atom_symbol:/⚛️/g
s/:om:/🕉️/g
s/:star_of_david:/✡️/g
s/:wheel_of_dharma:/☸️/g
s/:yin_yang:/☯️/g
s/:latin_cross:/✝️/g
s/:orthodox_cross:/☦️/g
s/:star_and_crescent:/☪️/g
s/:peace_symbol:/☮️/g
s/:menorah:/🕎/g
s/:six_pointed_star:/🔯/g
s/:aries:/♈/g
s/:taurus:/♉/g
s/:gemini:/♊/g
s/:cancer:/♋/g
s/:leo:/♌/g
s/:virgo:/♍/g
s/:libra:/♎/g
s/:scorpius:/♏/g
s/:sagittarius:/♐/g
s/:capricorn:/♑/g
s/:aquarius:/♒/g
s/:pisces:/♓/g
s/:ophiuchus:/⛎/g
s/:twisted_rightwards_arrows:/🔀/g
s/:repeat:/🔁/g
s/:repeat_one:/🔂/g
s/:arrow_forward:/▶️/g
s/:fast_forward:/⏩/g
s/:next_track_button:/⏭️/g
s/:play_or_pause_button:/⏯️/g
s/:arrow_backward:/◀️/g
s/:rewind:/⏪/g
s/:previous_track_button:/⏮️/g
s/:arrow_up_small:/🔼/g
s/:arrow_double_up:/⏫/g
s/:arrow_down_small:/🔽/g
s/:arrow_double_down:/⏬/g
s/:pause_button:/⏸️/g
s/:stop_button:/⏹️/g
s/:record_button:/⏺️/g
s/:eject_button:/⏏️/g
s/:cinema:/🎦/g
s/:low_brightness:/🔅/g
s/:high_brightness:/🔆/g
s/:signal_strength:/📶/g
s/:vibration_mode:/📳/g
s/:mobile_phone_off:/📴/g
s/:female_sign:/♀️/g
s/:male_sign:/♂️/g
s/:transgender_symbol:/⚧️/g
s/:heavy_multiplication_x:/✖️/g
s/:heavy_plus_sign:/➕/g
s/:heavy_minus_sign:/➖/g
s/:heavy_division_sign:/➗/g
s/:infinity:/♾️/g
s/:bangbang:/‼️/g
s/:interrobang:/⁉️/g
s/:question:/❓/g
s/:grey_question:/❔/g
s/:grey_exclamation:/❕/g
s/:\(exclamation\|heavy_exclamation_mark\):/❗/g
s/:wavy_dash:/〰️/g
s/:currency_exchange:/💱/g
s/:heavy_dollar_sign:/💲/g
s/:medical_symbol:/⚕️/g
s/:recycle:/♻️/g
s/:fleur_de_lis:/⚜️/g
s/:trident:/🔱/g
s/:name_badge:/📛/g
s/:beginner:/🔰/g
s/:o:/⭕/g
s/:white_check_mark:/✅/g
s/:ballot_box_with_check:/☑️/g
s/:heavy_check_mark:/✔️/g
s/:x:/❌/g
s/:negative_squared_cross_mark:/❎/g
s/:curly_loop:/➰/g
s/:loop:/➿/g
s/:part_alternation_mark:/〽️/g
s/:eight_spoked_asterisk:/✳️/g
s/:eight_pointed_black_star:/✴️/g
s/:sparkle:/❇️/g
s/:copyright:/©️/g
s/:registered:/®️/g
s/:tm:/™️/g
s/:hash:/#️⃣/g
s/:asterisk:/*️⃣/g
s/:zero:/0️⃣/g
s/:one:/1️⃣/g
s/:two:/2️⃣/g
s/:three:/3️⃣/g
s/:four:/4️⃣/g
s/:five:/5️⃣/g
s/:six:/6️⃣/g
s/:seven:/7️⃣/g
s/:eight:/8️⃣/g
s/:nine:/9️⃣/g
s/:keycap_ten:/🔟/g
s/:capital_abcd:/🔠/g
s/:abcd:/🔡/g
s/:1234:/🔢/g
s/:symbols:/🔣/g
s/:abc:/🔤/g
s/:a:/🅰️/g
s/:ab:/🆎/g
s/:b:/🅱️/g
s/:cl:/🆑/g
s/:cool:/🆒/g
s/:free:/🆓/g
s/:information_source:/ℹ️/g
s/:id:/🆔/g
s/:m:/Ⓜ️/g
s/:new:/🆕/g
s/:ng:/🆖/g
s/:o2:/🅾️/g
s/:ok:/🆗/g
s/:parking:/🅿️/g
s/:sos:/🆘/g
s/:up:/🆙/g
s/:vs:/🆚/g
s/:koko:/🈁/g
s/:sa:/🈂️/g
s/:u6708:/🈷️/g
s/:u6709:/🈶/g
s/:u6307:/🈯/g
s/:ideograph_advantage:/🉐/g
s/:u5272:/🈹/g
s/:u7121:/🈚/g
s/:u7981:/🈲/g
s/:accept:/🉑/g
s/:u7533:/🈸/g
s/:u5408:/🈴/g
s/:u7a7a:/🈳/g
s/:congratulations:/㊗️/g
s/:secret:/㊙️/g
s/:u55b6:/🈺/g
s/:u6e80:/🈵/g
s/:red_circle:/🔴/g
s/:orange_circle:/🟠/g
s/:yellow_circle:/🟡/g
s/:green_circle:/🟢/g
s/:large_blue_circle:/🔵/g
s/:purple_circle:/🟣/g
s/:brown_circle:/🟤/g
s/:black_circle:/⚫/g
s/:white_circle:/⚪/g
s/:red_square:/🟥/g
s/:orange_square:/🟧/g
s/:yellow_square:/🟨/g
s/:green_square:/🟩/g
s/:blue_square:/🟦/g
s/:purple_square:/🟪/g
s/:brown_square:/🟫/g
s/:black_large_square:/⬛/g
s/:white_large_square:/⬜/g
s/:black_medium_square:/◼️/g
s/:white_medium_square:/◻️/g
s/:black_medium_small_square:/◾/g
s/:white_medium_small_square:/◽/g
s/:black_small_square:/▪️/g
s/:white_small_square:/▫️/g
s/:large_orange_diamond:/🔶/g
s/:large_blue_diamond:/🔷/g
s/:small_orange_diamond:/🔸/g
s/:small_blue_diamond:/🔹/g
s/:small_red_triangle:/🔺/g
s/:small_red_triangle_down:/🔻/g
s/:diamond_shape_with_a_dot_inside:/💠/g
s/:radio_button:/🔘/g
s/:white_square_button:/🔳/g
s/:black_square_button:/🔲/g
s/:checkered_flag:/🏁/g
s/:triangular_flag_on_post:/🚩/g
s/:crossed_flags:/🎌/g
s/:black_flag:/🏴/g
s/:white_flag:/🏳️/g
s/:rainbow_flag:/🏳️‍🌈/g
s/:transgender_flag:/🏳️‍⚧️/g
s/:pirate_flag:/🏴‍☠️/g
s/:ascension_island:/🇦🇨/g
s/:andorra:/🇦🇩/g
s/:united_arab_emirates:/🇦🇪/g
s/:afghanistan:/🇦🇫/g
s/:antigua_barbuda:/🇦🇬/g
s/:anguilla:/🇦🇮/g
s/:albania:/🇦🇱/g
s/:armenia:/🇦🇲/g
s/:angola:/🇦🇴/g
s/:antarctica:/🇦🇶/g
s/:argentina:/🇦🇷/g
s/:american_samoa:/🇦🇸/g
s/:austria:/🇦🇹/g
s/:australia:/🇦🇺/g
s/:aruba:/🇦🇼/g
s/:aland_islands:/🇦🇽/g
s/:azerbaijan:/🇦🇿/g
s/:bosnia_herzegovina:/🇧🇦/g
s/:barbados:/🇧🇧/g
s/:bangladesh:/🇧🇩/g
s/:belgium:/🇧🇪/g
s/:burkina_faso:/🇧🇫/g
s/:bulgaria:/🇧🇬/g
s/:bahrain:/🇧🇭/g
s/:burundi:/🇧🇮/g
s/:benin:/🇧🇯/g
s/:st_barthelemy:/🇧🇱/g
s/:bermuda:/🇧🇲/g
s/:brunei:/🇧🇳/g
s/:bolivia:/🇧🇴/g
s/:caribbean_netherlands:/🇧🇶/g
s/:brazil:/🇧🇷/g
s/:bahamas:/🇧🇸/g
s/:bhutan:/🇧🇹/g
s/:bouvet_island:/🇧🇻/g
s/:botswana:/🇧🇼/g
s/:belarus:/🇧🇾/g
s/:belize:/🇧🇿/g
s/:canada:/🇨🇦/g
s/:cocos_islands:/🇨🇨/g
s/:congo_kinshasa:/🇨🇩/g
s/:central_african_republic:/🇨🇫/g
s/:congo_brazzaville:/🇨🇬/g
s/:switzerland:/🇨🇭/g
s/:cote_divoire:/🇨🇮/g
s/:cook_islands:/🇨🇰/g
s/:chile:/🇨🇱/g
s/:cameroon:/🇨🇲/g
s/:cn:/🇨🇳/g
s/:colombia:/🇨🇴/g
s/:clipperton_island:/🇨🇵/g
s/:costa_rica:/🇨🇷/g
s/:cuba:/🇨🇺/g
s/:cape_verde:/🇨🇻/g
s/:curacao:/🇨🇼/g
s/:christmas_island:/🇨🇽/g
s/:cyprus:/🇨🇾/g
s/:czech_republic:/🇨🇿/g
s/:de:/🇩🇪/g
s/:diego_garcia:/🇩🇬/g
s/:djibouti:/🇩🇯/g
s/:denmark:/🇩🇰/g
s/:dominica:/🇩🇲/g
s/:dominican_republic:/🇩🇴/g
s/:algeria:/🇩🇿/g
s/:ceuta_melilla:/🇪🇦/g
s/:ecuador:/🇪🇨/g
s/:estonia:/🇪🇪/g
s/:egypt:/🇪🇬/g
s/:western_sahara:/🇪🇭/g
s/:eritrea:/🇪🇷/g
s/:es:/🇪🇸/g
s/:ethiopia:/🇪🇹/g
s/:\(eu\|european_union\):/🇪🇺/g
s/:finland:/🇫🇮/g
s/:fiji:/🇫🇯/g
s/:falkland_islands:/🇫🇰/g
s/:micronesia:/🇫🇲/g
s/:faroe_islands:/🇫🇴/g
s/:fr:/🇫🇷/g
s/:gabon:/🇬🇦/g
s/:\(gb\|uk\):/🇬🇧/g
s/:grenada:/🇬🇩/g
s/:georgia:/🇬🇪/g
s/:french_guiana:/🇬🇫/g
s/:guernsey:/🇬🇬/g
s/:ghana:/🇬🇭/g
s/:gibraltar:/🇬🇮/g
s/:greenland:/🇬🇱/g
s/:gambia:/🇬🇲/g
s/:guinea:/🇬🇳/g
s/:guadeloupe:/🇬🇵/g
s/:equatorial_guinea:/🇬🇶/g
s/:greece:/🇬🇷/g
s/:south_georgia_south_sandwich_islands:/🇬🇸/g
s/:guatemala:/🇬🇹/g
s/:guam:/🇬🇺/g
s/:guinea_bissau:/🇬🇼/g
s/:guyana:/🇬🇾/g
s/:hong_kong:/🇭🇰/g
s/:heard_mcdonald_islands:/🇭🇲/g
s/:honduras:/🇭🇳/g
s/:croatia:/🇭🇷/g
s/:haiti:/🇭🇹/g
s/:hungary:/🇭🇺/g
s/:canary_islands:/🇮🇨/g
s/:indonesia:/🇮🇩/g
s/:ireland:/🇮🇪/g
s/:israel:/🇮🇱/g
s/:isle_of_man:/🇮🇲/g
s/:india:/🇮🇳/g
s/:british_indian_ocean_territory:/🇮🇴/g
s/:iraq:/🇮🇶/g
s/:iran:/🇮🇷/g
s/:iceland:/🇮🇸/g
s/:it:/🇮🇹/g
s/:jersey:/🇯🇪/g
s/:jamaica:/🇯🇲/g
s/:jordan:/🇯🇴/g
s/:jp:/🇯🇵/g
s/:kenya:/🇰🇪/g
s/:kyrgyzstan:/🇰🇬/g
s/:cambodia:/🇰🇭/g
s/:kiribati:/🇰🇮/g
s/:comoros:/🇰🇲/g
s/:st_kitts_nevis:/🇰🇳/g
s/:north_korea:/🇰🇵/g
s/:kr:/🇰🇷/g
s/:kuwait:/🇰🇼/g
s/:cayman_islands:/🇰🇾/g
s/:kazakhstan:/🇰🇿/g
s/:laos:/🇱🇦/g
s/:lebanon:/🇱🇧/g
s/:st_lucia:/🇱🇨/g
s/:liechtenstein:/🇱🇮/g
s/:sri_lanka:/🇱🇰/g
s/:liberia:/🇱🇷/g
s/:lesotho:/🇱🇸/g
s/:lithuania:/🇱🇹/g
s/:luxembourg:/🇱🇺/g
s/:latvia:/🇱🇻/g
s/:libya:/🇱🇾/g
s/:morocco:/🇲🇦/g
s/:monaco:/🇲🇨/g
s/:moldova:/🇲🇩/g
s/:montenegro:/🇲🇪/g
s/:st_martin:/🇲🇫/g
s/:madagascar:/🇲🇬/g
s/:marshall_islands:/🇲🇭/g
s/:macedonia:/🇲🇰/g
s/:mali:/🇲🇱/g
s/:myanmar:/🇲🇲/g
s/:mongolia:/🇲🇳/g
s/:macau:/🇲🇴/g
s/:northern_mariana_islands:/🇲🇵/g
s/:martinique:/🇲🇶/g
s/:mauritania:/🇲🇷/g
s/:montserrat:/🇲🇸/g
s/:malta:/🇲🇹/g
s/:mauritius:/🇲🇺/g
s/:maldives:/🇲🇻/g
s/:malawi:/🇲🇼/g
s/:mexico:/🇲🇽/g
s/:malaysia:/🇲🇾/g
s/:mozambique:/🇲🇿/g
s/:namibia:/🇳🇦/g
s/:new_caledonia:/🇳🇨/g
s/:niger:/🇳🇪/g
s/:norfolk_island:/🇳🇫/g
s/:nigeria:/🇳🇬/g
s/:nicaragua:/🇳🇮/g
s/:netherlands:/🇳🇱/g
s/:norway:/🇳🇴/g
s/:nepal:/🇳🇵/g
s/:nauru:/🇳🇷/g
s/:niue:/🇳🇺/g
s/:new_zealand:/🇳🇿/g
s/:oman:/🇴🇲/g
s/:panama:/🇵🇦/g
s/:peru:/🇵🇪/g
s/:french_polynesia:/🇵🇫/g
s/:papua_new_guinea:/🇵🇬/g
s/:philippines:/🇵🇭/g
s/:pakistan:/🇵🇰/g
s/:poland:/🇵🇱/g
s/:st_pierre_miquelon:/🇵🇲/g
s/:pitcairn_islands:/🇵🇳/g
s/:puerto_rico:/🇵🇷/g
s/:palestinian_territories:/🇵🇸/g
s/:portugal:/🇵🇹/g
s/:palau:/🇵🇼/g
s/:paraguay:/🇵🇾/g
s/:qatar:/🇶🇦/g
s/:reunion:/🇷🇪/g
s/:romania:/🇷🇴/g
s/:serbia:/🇷🇸/g
s/:ru:/🇷🇺/g
s/:rwanda:/🇷🇼/g
s/:saudi_arabia:/🇸🇦/g
s/:solomon_islands:/🇸🇧/g
s/:seychelles:/🇸🇨/g
s/:sudan:/🇸🇩/g
s/:sweden:/🇸🇪/g
s/:singapore:/🇸🇬/g
s/:st_helena:/🇸🇭/g
s/:slovenia:/🇸🇮/g
s/:svalbard_jan_mayen:/🇸🇯/g
s/:slovakia:/🇸🇰/g
s/:sierra_leone:/🇸🇱/g
s/:san_marino:/🇸🇲/g
s/:senegal:/🇸🇳/g
s/:somalia:/🇸🇴/g
s/:suriname:/🇸🇷/g
s/:south_sudan:/🇸🇸/g
s/:sao_tome_principe:/🇸🇹/g
s/:el_salvador:/🇸🇻/g
s/:sint_maarten:/🇸🇽/g
s/:syria:/🇸🇾/g
s/:swaziland:/🇸🇿/g
s/:tristan_da_cunha:/🇹🇦/g
s/:turks_caicos_islands:/🇹🇨/g
s/:chad:/🇹🇩/g
s/:french_southern_territories:/🇹🇫/g
s/:togo:/🇹🇬/g
s/:thailand:/🇹🇭/g
s/:tajikistan:/🇹🇯/g
s/:tokelau:/🇹🇰/g
s/:timor_leste:/🇹🇱/g
s/:turkmenistan:/🇹🇲/g
s/:tunisia:/🇹🇳/g
s/:tonga:/🇹🇴/g
s/:tr:/🇹🇷/g
s/:trinidad_tobago:/🇹🇹/g
s/:tuvalu:/🇹🇻/g
s/:taiwan:/🇹🇼/g
s/:tanzania:/🇹🇿/g
s/:ukraine:/🇺🇦/g
s/:uganda:/🇺🇬/g
s/:us_outlying_islands:/🇺🇲/g
s/:united_nations:/🇺🇳/g
s/:us:/🇺🇸/g
s/:uruguay:/🇺🇾/g
s/:uzbekistan:/🇺🇿/g
s/:vatican_city:/🇻🇦/g
s/:st_vincent_grenadines:/🇻🇨/g
s/:venezuela:/🇻🇪/g
s/:british_virgin_islands:/🇻🇬/g
s/:us_virgin_islands:/🇻🇮/g
s/:vietnam:/🇻🇳/g
s/:vanuatu:/🇻🇺/g
s/:wallis_futuna:/🇼🇫/g
s/:samoa:/🇼🇸/g
s/:kosovo:/🇽🇰/g
s/:yemen:/🇾🇪/g
s/:mayotte:/🇾🇹/g
s/:south_africa:/🇿🇦/g
s/:zambia:/🇿🇲/g
s/:zimbabwe:/🇿🇼/g
s/:england:/🏴󠁧󠁢󠁥󠁮󠁧󠁿/g
s/:scotland:/🏴󠁧󠁢󠁳󠁣󠁴󠁿/g
s/:wales:/🏴󠁧󠁢󠁷󠁬󠁳󠁿/g
