s/:trump_1:/🃡/g
s/:trump_2:/🃢/g
s/:trump_3:/🃣/g
s/:trump_4:/🃤/g
s/:trump_5:/🃥/g
s/:trump_6:/🃦/g
s/:trump_7:/🃧/g
s/:trump_8:/🃨/g
s/:trump_9:/🃩/g
s/:trump_10:/🃪/g
s/:trump_11:/🃫/g
s/:trump_12:/🃬/g
s/:trump_13:/🃭/g
s/:trump_14:/🃮/g
s/:trump_15:/🃯/g
s/:trump_16:/🃰/g
s/:trump_17:/🃱/g
s/:trump_18:/🃲/g
s/:trump_19:/🃳/g
s/:trump_20:/🃴/g
s/:trump_21:/🃵/g
