s/:card_\(1\|a\)h:/🂱/g
s/:card_2h:/🂲/g
s/:card_3h:/🂳/g
s/:card_4h:/🂴/g
s/:card_5h:/🂵/g
s/:card_6h:/🂶/g
s/:card_7h:/🂷/g
s/:card_8h:/🂸/g
s/:card_9h:/🂹/g
s/:card_\(10\|0\)h:/🂺/g
s/:card_jh:/🂻/g
s/:card_ch:/🂼/g
s/:card_qh:/🂽/g
s/:card_kh:/🂾/g

s/:card_\(1\|a\)d:/🃁/g
s/:card_2d:/🃂/g
s/:card_3d:/🃃/g
s/:card_4d:/🃄/g
s/:card_5d:/🃅/g
s/:card_6d:/🃆/g
s/:card_7d:/🃇/g
s/:card_8d:/🃈/g
s/:card_9d:/🃉/g
s/:card_\(10\|0\)d:/🃊/g
s/:card_jd:/🃋/g
s/:card_cd:/🃌/g
s/:card_qd:/🃍/g
s/:card_kd:/🃎/g

s/:card_\(1\|a\)c:/🃑/g
s/:card_2c:/🃒/g
s/:card_3c:/🃓/g
s/:card_4c:/🃔/g
s/:card_5c:/🃕/g
s/:card_6c:/🃖/g
s/:card_7c:/🃗/g
s/:card_8c:/🃘/g
s/:card_9c:/🃙/g
s/:card_\(10\|0\)c:/🃚/g
s/:card_jc:/🃛/g
s/:card_cc:/🃜/g
s/:card_qc:/🃝/g
s/:card_kc:/🃞/g

s/:card_\(1\|a\)s:/🂡/g
s/:card_2s:/🂢/g
s/:card_3s:/🂣/g
s/:card_4s:/🂤/g
s/:card_5s:/🂥/g
s/:card_6s:/🂦/g
s/:card_7s:/🂧/g
s/:card_8s:/🂨/g
s/:card_9s:/🂩/g
s/:card_\(10\|0\)s:/🂪/g
s/:card_js:/🂫/g
s/:card_cs:/🂬/g
s/:card_qs:/🂭/g
s/:card_ks:/🂮/g

s/:card_bk:/🂠/g
s/:card_rj:/🂿/g
s/:card_bj:/🃏/g
s/:card_wj:/🃟/g
